apiVersion: v1
appVersion: "1.0.0"
description: Serial to Socket Redirector
name: ser2sock
<<<<<<< HEAD
version: 1.1.0
=======
version: 1.1.2
>>>>>>> 3830980... [ser2sock] Added baudRate as a values option
keywords:
  - ser2sock
home: https://github.com/billimek/billimek-charts/tree/master/charts/ser2sock
icon: https://i.imgur.com/GfZ7McO.png
sources:
  - https://github.com/nutechsoftware/ser2sock
  - https://github.com/tenstartups/ser2sock
maintainers:
  - name: billimek
    email: jeff@billimek.com
