{{- if and (.Values.plex_autoscan.enabled) (.Values.plex_autoscan.ingress.enabled) }}
{{- $fullName := include "plex.fullname" . -}}
{{- $servicePort := .Values.plex_autoscan.config.SERVER_PORT -}}
{{- $ingressPath := .Values.plex_autoscan.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-plex_autoscan
  labels:
    app.kubernetes.io/name: {{ include "plex.name" . }}
    helm.sh/chart: {{ include "plex.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.plex_autoscan.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.plex_autoscan.ingress.tls }}
  tls:
  {{- range .Values.plex_autoscan.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.plex_autoscan.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
